-- Neovim 0.12 native config: vim.pack + native LSP (no LazyVim / lazy.nvim)
require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.pack")
require("config.lsp")
