-- Parser installation and query management with tree-sitter-manager.nvim.
require("tree-sitter-manager").setup({
  ensure_installed = {
    "bash",
    "c",
    "cmake",
    "cpp",
    "diff",
    "dockerfile",
    "git_config",
    "gitcommit",
    "gitignore",
    "haskell",
    "hocon",
    "html",
    "java",
    "javascript",
    "json",
    "json5",
    "kotlin",
    "lua",
    "luadoc",
    "luap",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "regex",
    "rust",
    "terraform",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "yaml",
  },
  auto_install = true,
  highlight = true,
})

vim.filetype.add({ extension = { conf = "hocon" } })
