-- Treesitter (master branch classic API)
require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "bash",
    "c",
    "cmake",
    "cpp",
    "diff",
    "dockerfile",
    "git_config",
    "gitcommit",
    "gitignore",
    "haskell",
    "hocon",
    "html",
    "java",
    "javascript",
    "json",
    "json5",
    "jsonc",
    "kotlin",
    "lua",
    "luadoc",
    "luap",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "regex",
    "terraform",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "yaml",
  },
  auto_install = true,
  highlight = { enable = true },
  indent = { enable = true },
})

-- Map .conf files to hocon
vim.filetype.add({ extension = { conf = "hocon" } })
